language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
before_script:
    - composer install --no-progress
script:
    - ./vendor/bin/security-checker security:check composer.lock
    - ./vendor/bin/phpcs --standard=PSR2 --ignore=vendor/ .
    - ./vendor/bin/phpmd --exclude vendor/ . text ruleset.xml
    - ./vendor/bin/phpunit
